/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/carrt/ros-hydro/carrt_ws/src/collab/msg/Intention.msg
 *
 */


#ifndef COLLAB_MESSAGE_INTENTION_H
#define COLLAB_MESSAGE_INTENTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <collab/ObjectProperties.h>

namespace collab
{
template <class ContainerAllocator>
struct Intention_
{
  typedef Intention_<ContainerAllocator> Type;

  Intention_()
    : objectName()
    , actionName()
    , objectProperties()  {
    }
  Intention_(const ContainerAllocator& _alloc)
    : objectName(_alloc)
    , actionName(_alloc)
    , objectProperties(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _objectName_type;
  _objectName_type objectName;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _actionName_type;
  _actionName_type actionName;

   typedef  ::collab::ObjectProperties_<ContainerAllocator>  _objectProperties_type;
  _objectProperties_type objectProperties;




  typedef boost::shared_ptr< ::collab::Intention_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::collab::Intention_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Intention_

typedef ::collab::Intention_<std::allocator<void> > Intention;

typedef boost::shared_ptr< ::collab::Intention > IntentionPtr;
typedef boost::shared_ptr< ::collab::Intention const> IntentionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::collab::Intention_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::collab::Intention_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace collab

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'collab': ['/home/carrt/ros-hydro/carrt_ws/src/collab/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::collab::Intention_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collab::Intention_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collab::Intention_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collab::Intention_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collab::Intention_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collab::Intention_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::collab::Intention_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b7253dcc2556d1a8f3e26a7e2fc6350";
  }

  static const char* value(const ::collab::Intention_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b7253dcc2556d1aULL;
  static const uint64_t static_value2 = 0x8f3e26a7e2fc6350ULL;
};

template<class ContainerAllocator>
struct DataType< ::collab::Intention_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collab/Intention";
  }

  static const char* value(const ::collab::Intention_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::collab::Intention_<ContainerAllocator> >
{
  static const char* value()
  {
    return "######################\n\
# Object-Action Pair #\n\
######################\n\
string objectName\n\
string actionName\n\
\n\
#####################\n\
# Object Properties #\n\
#####################\n\
ObjectProperties objectProperties\n\
\n\
================================================================================\n\
MSG: collab/ObjectProperties\n\
# (c) K. Duncan, 2015\n\
# Represents an object in terms of its associated superquadric parameters\n\
# and the object's category identity.\n\
\n\
############\n\
# Identity #\n\
############\n\
string objectName\n\
\n\
\n\
########################\n\
# Geometric Properties #\n\
########################\n\
# The shape dimension for the x-axis\n\
float64 a1\n\
\n\
# The shape dimension for the y-axis\n\
float64 a2\n\
\n\
# The shape dimension for the z-axis\n\
float64 a3\n\
\n\
# The x-axis location of the centroid of this superquadric\n\
float64 px\n\
\n\
# The y-axis location of the centroid of this superquadric\n\
float64 py\n\
\n\
# The z-axis location of the centroid of this superquadric\n\
float64 pz\n\
\n\
# Euler rotation angle along the x-axis\n\
float64 phi\n\
\n\
# Euler rotation angle along the y-axis\n\
float64 theta\n\
\n\
# Euler rotation angle along the x-axis\n\
float64 psi\n\
";
  }

  static const char* value(const ::collab::Intention_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::collab::Intention_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objectName);
      stream.next(m.actionName);
      stream.next(m.objectProperties);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Intention_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::collab::Intention_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::collab::Intention_<ContainerAllocator>& v)
  {
    s << indent << "objectName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.objectName);
    s << indent << "actionName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.actionName);
    s << indent << "objectProperties: ";
    s << std::endl;
    Printer< ::collab::ObjectProperties_<ContainerAllocator> >::stream(s, indent + "  ", v.objectProperties);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLLAB_MESSAGE_INTENTION_H
