/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/carrt/ros-hydro/carrt_ws/src/collab/msg/SceneComposition.msg
 *
 */


#ifndef COLLAB_MESSAGE_SCENECOMPOSITION_H
#define COLLAB_MESSAGE_SCENECOMPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <collab/ObjectProperties.h>

namespace collab
{
template <class ContainerAllocator>
struct SceneComposition_
{
  typedef SceneComposition_<ContainerAllocator> Type;

  SceneComposition_()
    : sceneComposition()  {
    }
  SceneComposition_(const ContainerAllocator& _alloc)
    : sceneComposition(_alloc)  {
    }



   typedef std::vector< ::collab::ObjectProperties_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::collab::ObjectProperties_<ContainerAllocator> >::other >  _sceneComposition_type;
  _sceneComposition_type sceneComposition;




  typedef boost::shared_ptr< ::collab::SceneComposition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::collab::SceneComposition_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct SceneComposition_

typedef ::collab::SceneComposition_<std::allocator<void> > SceneComposition;

typedef boost::shared_ptr< ::collab::SceneComposition > SceneCompositionPtr;
typedef boost::shared_ptr< ::collab::SceneComposition const> SceneCompositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::collab::SceneComposition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::collab::SceneComposition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace collab

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'collab': ['/home/carrt/ros-hydro/carrt_ws/src/collab/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::collab::SceneComposition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::collab::SceneComposition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collab::SceneComposition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::collab::SceneComposition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collab::SceneComposition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::collab::SceneComposition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::collab::SceneComposition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fcfa93db164857c0fe4d73defd9c033c";
  }

  static const char* value(const ::collab::SceneComposition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfcfa93db164857c0ULL;
  static const uint64_t static_value2 = 0xfe4d73defd9c033cULL;
};

template<class ContainerAllocator>
struct DataType< ::collab::SceneComposition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collab/SceneComposition";
  }

  static const char* value(const ::collab::SceneComposition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::collab::SceneComposition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "collab/ObjectProperties[] sceneComposition\n\
================================================================================\n\
MSG: collab/ObjectProperties\n\
# (c) K. Duncan, 2015\n\
# Represents an object in terms of its associated superquadric parameters\n\
# and the object's category identity.\n\
\n\
############\n\
# Identity #\n\
############\n\
string objectName\n\
\n\
\n\
########################\n\
# Geometric Properties #\n\
########################\n\
# The shape dimension for the x-axis\n\
float64 a1\n\
\n\
# The shape dimension for the y-axis\n\
float64 a2\n\
\n\
# The shape dimension for the z-axis\n\
float64 a3\n\
\n\
# The x-axis location of the centroid of this superquadric\n\
float64 px\n\
\n\
# The y-axis location of the centroid of this superquadric\n\
float64 py\n\
\n\
# The z-axis location of the centroid of this superquadric\n\
float64 pz\n\
\n\
# Euler rotation angle along the x-axis\n\
float64 phi\n\
\n\
# Euler rotation angle along the y-axis\n\
float64 theta\n\
\n\
# Euler rotation angle along the x-axis\n\
float64 psi\n\
";
  }

  static const char* value(const ::collab::SceneComposition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::collab::SceneComposition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sceneComposition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SceneComposition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::collab::SceneComposition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::collab::SceneComposition_<ContainerAllocator>& v)
  {
    s << indent << "sceneComposition[]" << std::endl;
    for (size_t i = 0; i < v.sceneComposition.size(); ++i)
    {
      s << indent << "  sceneComposition[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::collab::ObjectProperties_<ContainerAllocator> >::stream(s, indent + "    ", v.sceneComposition[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLLAB_MESSAGE_SCENECOMPOSITION_H
